[#chapter-section1]
= Composition Rules

There are several rules you must follow to successfully convert your AsciiDoc source documents into an EPUB3 publication archive.
These rules may be loosened in the future, but they are mandatory at the moment.

Rule 1::
Each chapter must begin in a dedicated file that resides at the root of the project.
It must be included into the main document using the AsciiDoc include directive.
The main document, which we call the “spine”, may only contain a document header and a sequence of include directives.
See <<Declaring the Spine>> for details.
+
TIP: The include directive may be used in the chapter files to include other files (even files in other folders).

Rule 2::
Each chapter must start with a document title (i.e., level-0 heading).
The document header must declare an ID that matches the chapter filename (minus its file extension).

Rule 3::
No sections in a chapter may have the same ID as the chapter ID.

Rule 4::
The cross reference (i.e., xref) from one chapter to another must be in the format `+xref:chapter-id#chapter-id[optional reftext]+` (or `+<<chapter-id#chapter-id,optional reftext>>+`).
If you want to reference a section in a chapter, update the fragment (i.e., the value that follows the hash) to match the target section ID.
The reftext is optional since the reftext of the target is used by default.
+
TIP: To assign reference text (i.e., reftext) to chapter title, use the document attribute named `docreftext`.
+
TIP: Rule 2 states that the chapter ID must match the basename of the chapter file.
In truth, the chapter ID can be a _derivative of_ the chapter filename.
In that case, an attribute reference can be used to prepend a prefix to an inter-document cross reference.
For example, if you want each chapter file to begin with `chapter-`, you'd write the xref as `+xref:{chapter-prefix}chapter-id#chapter-id[]+`.
You'd then assign an empty value to the `chapter-prefix` attribute when converting to an ebook and `chapter-` for all other formats.

The next section goes into more detail about how to set up the spine document and include the chapter files.
